FROM mcr.microsoft.com/dotnet/aspnet:7.0  AS base
COPY bin/Release/net7.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep authserver.pfx -p 3eefc93e-5453-4229-b420-33ca5a50a43d

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "FaceAPI.HttpApi.Host.dll"]